### PR TITLE
Setters for Issue/PR

### PR DESCRIPTION
**Pull request by mfocko**

### CODE REVIEW

**Comment by mfocko** [comment]
Issue setters for Pagure are not implemented since there's (apparently) no API support for that and I haven't managed to find any issue on Pagure's repo related to it

**Comment by lachmanfrantisek** [comment]
> Issue setters for Pagure are not implemented since there's (apparently) no API support for that and I haven't managed to find any issue on Pagure's repo related to it

Can you create a new issue on the Pagure site, please? Also, please add the link here, so we have them linked together.

**Comment by mfocko** [comment]
> > Issue setters for Pagure are not implemented since there's (apparently) no API support for that and I haven't managed to find any issue on Pagure's repo related to it
> 
> Can you create a new issue on the Pagure site, please? Also, please add the link here, so we have them linked together.

done: https://github.com/packit-service/ogr/issues/302

**Comment by lachmanfrantisek** [comment]
> done: #302

Thanks!

**Comment by lachmanfrantisek** [comment]
>     * [ogr-pre-commit ](https://softwarefactory-project.io/zuul/t/local/build/b423a1ec8fa345a691ab3f09b19ab4ec) : FAILURE in 3m 26s

@mfocko Rebase please..

**Pull request merged**
