### PR TITLE
Allow to filter issues by labels.

### PR DESCRIPTION
**Pull request by cverna**
This commit adds the possibility to provide
a list of labels to filter the issues of a
project.

Signed-off-by: Clement Verna <cverna@tutanota.com>

### CODE REVIEW

**Comment by cverna** [comment]
I would be happy to add tests but I need a few pointers on how to regenerate the data used by the integration tests.

**Comment by lachmanfrantisek** [comment]
> I would be happy to add tests but I need a few pointers on how to regenerate the data used by the integration tests.

The workflow should work like this:

1. Add a new test.
2. Run the tests with the authentication tokens (`env GITHUB_TOKEN="???" PAGURE_TOKEN="???" make check`)
  - This is the write mode and will use your authentication for connecting to the real servers. (It will save the responses to the YAML files.
3. Run the tests without tokens to check, that the responses were saved.
  - This "read-mode" is used in the CI.
  - It will load and replay the responses from the YAML file.

If the `write` does not work for you, sent at least the tests -- @jscotka made some changes in requre (the saving/replaying library we are using) and it may need some changes in the ogr to make it work as before.

**Comment by cverna** [comment]
> > I would be happy to add tests but I need a few pointers on how to regenerate the data used by the integration tests.
> 
> The workflow should work like this:
> 
>     1. Add a new test.
> 
>     2. Run the tests with the authentication tokens (`env GITHUB_TOKEN="???" PAGURE_TOKEN="???" make check`)
> 
> 
>     * This is the write mode and will use your authentication for connecting to the real servers. (It will save the responses to the YAML files.
> 
> 
>     1. Run the tests without tokens to check, that the responses were saved.
> 
> 
>     * This "read-mode" is used in the CI.
> 
>     * It will load and replay the responses from the YAML file.
> 
> 
> If the `write` does not work for you, sent at least the tests -- @jscotka made some changes in requre (the saving/replaying library we are using) and it may need some changes in the ogr to make it work as before.
> 
> If you need to regenerate an existing test, just remove the related response file and rerun the tests with the tokens.

Thanks I have added tests for Pagure and GitHub , I don't have a account/token for GitLab.

**Comment by lachmanfrantisek** [comment]
@cverna thanks!

Can you please rebase? (Not sure if you don't need to regenerate the response files because of the last PR by @jscotka . Sorry about that.)

I'll take care of the GitLab.

**Comment by cverna** [comment]
> @cverna thanks!
> 
> Can you please rebase? (Not sure if you don't need to regenerate the response files because of the last PR by @jscotka . Sorry about that.)

I did the rebase but the tests are failing :), not sure what I have to regenerate, only the files for the tests I have added ? or the whole set ?
The tests are also failing in the latest master in my local checkout.

> 
> I'll take care of the GitLab.

**Comment by lachmanfrantisek** [comment]
- You probably need the fresh version of [requre](https://github.com/packit-service/requre).
- You only need to regenerate the response files for the new tests.
- Do you want to try that once again? (..;-)  Or should I do it?

**Comment by cverna** [comment]
>     * You probably need the fresh version of [requre](https://github.com/packit-service/requre).
> 
>     * You only need to regenerate the response files for the new tests.
> 
>     * Do you want to try that once again? (..;-)  Or should I do it?

I would not mind if you could do it :-)

**Comment by lachmanfrantisek** [comment]
> I would not mind if you could do it :-)

OK, no problem. I'll send the changes to this PR...

**Comment by lachmanfrantisek** [comment]
I've tried to [create the GitLab issues for testing](https://gitlab.com/packit-service/ogr-tests/issues) automatically...;)
```
GitlabHttpError: 400: {'error': 'Spam detected'}
```

**Comment by cverna** [comment]
> I've tried to [create the GitLab issues for testing](https://gitlab.com/packit-service/ogr-tests/issues) automatically...;)
> 
> ```
> GitlabHttpError: 400: {'error': 'Spam detected'}
> ```

Haha nice one :)

**Comment by lachmanfrantisek** [comment]
I've already fixed the problem with pagination (#339) in Gitlab.

The files you generated were correct. I only needed to move them and run the clean script (done by [pre-commit](https://github.com/packit-service/ogr/blob/master/.pre-commit-config.yaml#L42))

**Comment by TomasTomecek** [comment]
recheck

**Pull request merged**
