### PR TITLE
Using pagination to retrieve pagure's full issue list

### LINKED ISSUE #339: support pagination for get_issue_list
Currently using a Pagure service the get_issue_list method returns only the last 20 issues of a project. This is because Pagure paginate the results, I have not looked at GitHub and GitLab but I guess it works the same.

Ideally `get_issue_list` should return a list of all the issues for a project and the pagination should be transparent to the user.

### PR DESCRIPTION
**Pull request by AdarLavi**
Fixes #339 
Pagure's API allows [pagination with 100 issues per page](https://pagure.io/api/0/#issues), this code iterates though issues pages until reaching either max issues (default 1000) or last issue.

### CODE REVIEW

**Comment by lachmanfrantisek** [comment]
@cverna, can you please take a quick look since you were already looking into that? Thanks!

**Comment by cverna** [comment]
@AdarLavi did you try using the 'pagination' section for the API ? that will give you the first, last and next page of a project. That way you would not need to have a max_issue variable.

The response looks like that 
`
 'pagination': {
    'first': 'http://localhost/api/0/test/issues?per_page=20&page=1',
    'last': 'http://localhost/api/0/test/issues?per_page=20&page=1',
    'next': null,
    'page': 1,
    'pages': 1,
    'per_page': 20,
    'prev': null

`

More info here https://pagure.io/api/0/#issues-tab

What do you think ?

**Comment by AdarLavi** [comment]
Hi @cverna, thank you for your input!
When I thought about how to implement this I was thinking about what will be the proper input from the user. As the API's pagination might be changed in the future I feel the `max_issues` is a more stable parameter for this method.
I'm sure how the `pagionation` metadata could help me in this case. Is there something I'm missing?

**Comment by lachmanfrantisek** [comment]
@cverna thanks!

@AdarLavi see the https://pagure.io/api/0/pagure/issues it contains maybe a better example:

- 1st: https://pagure.io/api/0/pagure/issues

| pagination |  
| -- | -- |
| first | "https://pagure.io/api/0/pagure/issues?per_page=20&page=1" |
| last | "https://pagure.io/api/0/pagure/issues?per_page=20&page=23" |
| next | "https://pagure.io/api/0/pagure/issues?per_page=20&page=2" |
| page | 1|
| pages | 23 |
| per_page | 20 |
| prev | null |
| total_issues | 20 |

- last: https://pagure.io/api/0/pagure/issues?per_page=20&page=23

| pagination |  
| -- | -- |
| first | "https://pagure.io/api/0/pagure/issues?per_page=20&page=1" |
| last | "https://pagure.io/api/0/pagure/issues?per_page=20&page=23" |
| next | null |
| page | 23 |
| pages | 23 |
| per_page | 20 |
| prev | "https://pagure.io/api/0/pagure/issues?per_page=20&page=22" |
| total_issues | 7 |

**Comment by AdarLavi** [comment]
thanks @lachmanfrantisek !
Even though the metadata contains the amount of issues per page, the amount of pages and how many issues there are in the last page, it all still depends on the amount of issues per page; that might be changed in the future in the API (for example, what if it'll allow retriving 1000 issues per page?).
I feel that asking the user to input the amount of `max_issues` he/she desires is more suitable, as the implementation shouldn't concern the developer. In addition, it allows changes in the implementation without changing the method signature.
Does that make sense?

**Comment by lachmanfrantisek** [comment]
> I feel that asking the user to input the amount of max_issues he/she desires is more suitable, as the implementation shouldn't concern the developer.

Do you think someone wants to use that from the Python code? For me, it's an implementation detail for communication to the server. Users just want all issues (as quickly as possible...;).

Some lazy/iterator approach is another topic -- see #325 (Still, it should be hidden to user.)

**Comment by lachmanfrantisek** [comment]
@AdarLavi in all cases, thanks for the contribution!

**Comment by AdarLavi** [comment]
hi @lachmanfrantisek,
I reviewed your refernce and now understand what you mean.
could you review the latest push?

**Comment by lachmanfrantisek** [comment]
recheck

**Comment by lachmanfrantisek** [comment]
@AdarLavi Thank you for the contribution!

**Pull request merged**
