### PR TITLE
added function to update mapping

### PR DESCRIPTION
**Pull request by sakalosj**

### CODE REVIEW

**Comment by TomasTomecek** [comment]
care to elaborate on what this change is about?

**Comment by sakalosj** [comment]
> care to elaborate on what this change is about?

When i wanted to use "git.stg.centos.org" it was raising error of missing maaping. I noticed that this can be fixed by decorating PagureService:
https://github.com/packit-service/ogr/blob/fe64b280c0fd5ef15d79991c233c67c9888ae486/ogr/services/pagure/service.py#L39-L41

I dont think this is best approach in my use case. This function is replacing usage of `use_for_service` decorator.

**Comment by lachmanfrantisek** [comment]
> I dont think this is best approach in my use case. This function is replacing usage of `use_for_service` decorator.

- Adding a new decorator should fix it for you. (It's a same way how we use it for Fedora distgit.)
- Or, factory methods have a way to add custom mapping:

https://github.com/packit-service/ogr/blob/fe64b280c0fd5ef15d79991c233c67c9888ae486/ogr/factory.py#L68-L73


https://github.com/packit-service/ogr/blob/fe64b280c0fd5ef15d79991c233c67c9888ae486/ogr/factory.py#L107-L109

https://github.com/packit-service/ogr/blob/fe64b280c0fd5ef15d79991c233c67c9888ae486/ogr/factory.py#L129-L131

**Comment by csomh** [comment]
> care to elaborate on what this change is about?

I would also like to see a clear explanation for *why* this is done, in the commit or PR message (or even both) and what is the issue that tries to solve.

Explanations in PR discussions are nice, but they don't scale:

1. you have to ask for them, as Tomas did -> waste of cycles; 
2. once PRs are merged and the change is in the main Git history, it's really cumbersome to trace back and find the relevant discussions in GitHub (assuming you have a working internet connection of course).

So let's try to do our best and be more verbose in our commit messages. There is nothing wrong about writing one paragraph of explanation for a one line change, especially if that helps reviewers be less confused.

**Comment by sakalosj** [comment]
> > care to elaborate on what this change is about?
> 
> I would also like to see a clear explanation for _why_ this is done, in the commit or PR message (or even both) and what is the issue that tries to solve.
> 
> Explanations in PR discussions are nice, but they don't scale:
> 
> 1. you have to ask for them, as Tomas did -> waste of cycles;
> 2. once PRs are merged and the change is in the main Git history, it's really cumbersome to trace back and find the relevant discussions in GitHub (assuming you have a working internet connection of course).
> 
> So let's try to do our best and be more verbose in our commit messages. There is nothing wrong about writing one paragraph of explanation for a one line change, especially if that helps reviewers be less confused.

agree with you, I will  focus on creating a higher quality pr/issues.

**Comment by sakalosj** [comment]
> > I dont think this is best approach in my use case. This function is replacing usage of `use_for_service` decorator.
> 
> * What is bad with the decorator? (It's the same way how we use it for Fedora distgit.)
> * Or, factory methods have a way to add custom mapping:
> 
> https://github.com/packit-service/ogr/blob/fe64b280c0fd5ef15d79991c233c67c9888ae486/ogr/factory.py#L68-L73
> 
> https://github.com/packit-service/ogr/blob/fe64b280c0fd5ef15d79991c233c67c9888ae486/ogr/factory.py#L107-L109
> 
> https://github.com/packit-service/ogr/blob/fe64b280c0fd5ef15d79991c233c67c9888ae486/ogr/factory.py#L129-L131

regarding decorator -  i have ot edit different project to have custom configuration in place
regarding factory method - this is good approach, but is somehow deeply wired into

**Pull request closed without merging**
