### PR TITLE
[spec] bump to 0.4.0

### PR DESCRIPTION
**Pull request by jpopelka**

### CODE REVIEW

**Comment by TomasTomecek** [comment]
we need to address this in packit finally

**Comment by jpopelka** [comment]
> we need to address this in packit finally

in packit or in release-bot (https://github.com/user-cont/release-bot/issues/228) ?

**Comment by TomasTomecek** [comment]
definitely in packit; but can be done in r-bot as well

**Comment by jpopelka** [comment]
Can you fill a packit issue then, the workflow is unclear to me.

**Comment by TomasTomecek** [comment]
https://github.com/packit-service/packit/issues/175

**Pull request merged**
