### PR TITLE
temporary integration test method PullRequest._pr_close_temp() removed

### PR DESCRIPTION
**Pull request by sakalosj**

### CODE REVIEW

**Comment by sakalosj** [comment]
is it possible to disable triggering of checks/builds on test branches test_source and test_target in hello-world repository?

**Comment by lachmanfrantisek** [comment]
> is it possible to disable triggering of checks/builds on test branches test_source and test_target in hello-world repository?

We cannot blacklist the branches, but you can try to remove the `packit.yaml` config file so the build should not be triggered.

We are using that repo for testing the Packit-as-a-Service so we need to have the app(s) enabled.

**Comment by sakalosj** [comment]
> > is it possible to disable triggering of checks/builds on test branches test_source and test_target in hello-world repository?
> 
> We cannot blacklist the branches, but you can try to remove the `packit.yaml` config file so the build should not be triggered.
> 
> We are using that repo for testing the Packit-as-a-Service so we need to have the app(s) enabled.

ok

**Comment by sakalosj** [comment]
i have removed .packit.yaml and build is not triggered anymore.

@lachmanfrantisek if there is nothing else i thinnk it can be merged

**Comment by lachmanfrantisek** [comment]
> @lachmanfrantisek if there is nothing else i thinnk it can be merged

Thanks!

**Pull request merged**
