### PR TITLE
Prepare file structure for object-specific methods

### LINKED ISSUE #232: Prepare file structure for object-specific methods (#86)
Split service implementations into separate directories, module for each class

- [x] Directory for each service
- [x] GitHub
  - [x] split implementation into multiple modules
  - [x] add `__init__.py` to make imports compatible
  - [x] update tests, since they store "full path" of caller
- [x] GitLab
  - [x] split implementation into multiple modules
  - [x] add `__init__.py` to make imports compatible
  - [x] update tests, since they store "full path" of caller
- [x] Pagure
  - [x] split implementation into multiple modules
  - [x] add `__init__.py` to make imports compatible
  - [x] update tests, since they store "full path" of caller

Related to #86

### PR DESCRIPTION
**Pull request by mfocko**
Fixes #232

### CODE REVIEW

**Comment by lachmanfrantisek** [comment]
@mfocko can I send you a fix for github to your branch? (You can use the same approach for other implementations.)

**Comment by mfocko** [comment]
> @mfocko can I send you a fix for github to your branch? (You can use the same approach for other implementations.)

Sure, added you to repo

**Comment by lachmanfrantisek** [comment]
@mfocko Waiting for #238 can help you a bit.

**Comment by lachmanfrantisek** [comment]
Tested:

- [x] packit
- [x] packit-service (fixed: https://github.com/packit-service/packit-service/pull/162)
- [x] release-bot (unrelated comptaiblity fix: https://github.com/user-cont/release-bot/pull/240)

**Pull request merged**
