### PR TITLE
Use strings for type annotations

### LINKED ISSUE #13: missing annotations library for testing
after installing `ogr` via ``pip3 install .``
I wanted to run make check ``PYTHONPATH=`pwd` pytest-3 -v ./tests/``

it leads to errors like:
```
E     File "/home/jscotka/git/userspace-containerization/ogr/ogr/abstract.py", line 1
E       from __future__ import annotations
E                                        ^
E   SyntaxError: future feature annotations is not defined
```

seems that annotations module is not accessible in ``python3-3.6.8-1.fc28.x86_64`` by default

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
- Remove future import for annotations => python3.6 compatibility.

Resolves #13

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Since you're so brave to work on this, I challenge you to also set up testing in python36 using tox:

https://developer.fedoraproject.org/tech/languages/python/multiple-pythons.html

**Comment by lachmanfrantisek** [comment]
> Since you're so brave to work on this, I challenge you to also set up testing in python36 using tox:

Let's discuss the tox tomorrow.

**Comment by lachmanfrantisek** [comment]
Dataclasses fixed, but in `packit`, we also have some.

**Comment by jpopelka** [comment]
>  set up testing in python36 using tox

good idea, but for another pr, I've added it to #8

**Comment by TomasTomecek** [comment]
https://github.com/packit-service/packit/issues/57

**Pull request merged**
